{
 "title": "Prosys Simulation Server",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Counter (Last known)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT timestamp AS time,\r\n       --((sum(value) * 1000) %(1000*60*60))%(1000*60)/1000  AS \"Running\"\r\n       value AS \"Running\"\r\nFROM ('sensors' timestamp(timestamp))\r\nWHERE tag='NodeId ns=3;i=1002' \r\n      AND $__timeFilter(timestamp)\r\n--SAMPLE BY $__interval;",
     "selectedFormat": 2
    }
   ]
  },
  {
   "title": "Sawtooth (Last known)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT timestamp AS time,\r\n       --((sum(value) * 1000) %(1000*60*60))%(1000*60)/1000  AS \"Running\"\r\n       value AS \"Running\"\r\nFROM ('sensors' timestamp(timestamp))\r\nWHERE tag='NodeId ns=3;i=1004' \r\n      AND $__timeFilter(timestamp)\r\n--SAMPLE BY $__interval;",
     "selectedFormat": 2
    }
   ]
  },
  {
   "title": "Sinusoid (Last known)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 11, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT timestamp AS time,\r\n       --((sum(value) * 1000) %(1000*60*60))%(1000*60)/1000  AS \"Running\"\r\n       value AS \"Running\"\r\nFROM ('sensors' timestamp(timestamp))\r\nWHERE tag='NodeId ns=3;i=1005' \r\n      AND $__timeFilter(timestamp)\r\n--SAMPLE BY $__interval;",
     "selectedFormat": 2
    }
   ]
  },
  {
   "title": "Triangle (Last known)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT timestamp AS time,\r\n       --((sum(value) * 1000) %(1000*60*60))%(1000*60)/1000  AS \"Running\"\r\n       value AS \"Running\"\r\nFROM ('sensors' timestamp(timestamp))\r\nWHERE tag='NodeId ns=3;i=1007' \r\n      AND $__timeFilter(timestamp)\r\n--SAMPLE BY $__interval;",
     "selectedFormat": 2
    }
   ]
  },
  {
   "title": "Sawtooth",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 3 },
   "targets": [
    {
     "rawSql": "SELECT timestamp AS time,\r\n       --((sum(value) * 1000) %(1000*60*60))%(1000*60)/1000  AS \"Running\"\r\n       value AS \"Running\"\r\nFROM ('sensors' timestamp(timestamp))\r\nWHERE tag='NodeId ns=3;i=1004' \r\n      AND $__timeFilter(timestamp)\r\n--SAMPLE BY $__interval;",
     "selectedFormat": 2
    }
   ]
  },
  {
   "title": "Random",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 13, "x": 11, "y": 3 },
   "targets": [
    {
     "rawSql": "SELECT timestamp AS time,\r\n       --((sum(value) * 1000) %(1000*60*60))%(1000*60)/1000  AS \"Running\"\r\n       value AS \"Running\"\r\nFROM ('sensors' timestamp(timestamp))\r\nWHERE tag='NodeId ns=3;i=1003' \r\n      AND $__timeFilter(timestamp)\r\n--SAMPLE BY $__interval;",
     "selectedFormat": 2
    }
   ]
  },
  {
   "title": "Square",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT timestamp AS time,\r\n       --((sum(value) * 1000) %(1000*60*60))%(1000*60)/1000  AS \"Running\"\r\n       value AS \"Running\"\r\nFROM ('sensors' timestamp(timestamp))\r\nWHERE tag='NodeId ns=3;i=1006' \r\n      AND $__timeFilter(timestamp)\r\n--SAMPLE BY $__interval;",
     "selectedFormat": 2
    }
   ]
  },
  {
   "title": "Sinusiod",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 13, "x": 11, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT timestamp AS time,\r\n       --((sum(value) * 1000) %(1000*60*60))%(1000*60)/1000  AS \"Running\"\r\n       value AS \"Running\"\r\nFROM ('sensors' timestamp(timestamp))\r\nWHERE tag='NodeId ns=3;i=1005' \r\n      AND $__timeFilter(timestamp)\r\n--SAMPLE BY $__interval;",
     "selectedFormat": 2
    }
   ]
  },
  {
   "title": "Counter",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 17 },
   "targets": [
    {
     "rawSql": "SELECT timestamp AS time,\r\n       --((sum(value) * 1000) %(1000*60*60))%(1000*60)/1000  AS \"Running\"\r\n       value AS \"Running\"\r\nFROM ('sensors' timestamp(timestamp))\r\nWHERE tag='NodeId ns=3;i=1002' \r\n      AND $__timeFilter(timestamp)\r\n--SAMPLE BY $__interval;",
     "selectedFormat": 2
    }
   ]
  },
  {
   "title": "Triangle",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 13, "x": 11, "y": 17 },
   "targets": [
    {
     "rawSql": "SELECT timestamp AS time,\r\n       --((sum(value) * 1000) %(1000*60*60))%(1000*60)/1000  AS \"Running\"\r\n       value AS \"Running\"\r\nFROM ('sensors' timestamp(timestamp))\r\nWHERE tag='NodeId ns=3;i=1007' \r\n      AND $__timeFilter(timestamp)\r\n--SAMPLE BY $__interval;",
     "selectedFormat": 2
    }
   ]
  }
 ]
}